# Generated by Django 3.2.9 on 2022-02-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_alter_cart_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_items',
            field=models.ManyToManyField(blank=True, to='carts.CartItem'),
        ),
    ]
