# Generated by Django 3.2.9 on 2022-03-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0022_cartitem_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='subtotal',
        ),
    ]
