# Generated by Django 3.2.9 on 2022-03-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0023_auto_20220310_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery',
            field=models.CharField(blank=True, choices=[('P', 'Pick-up'), ('N', 'Normal Delivery'), ('F', 'Fast Delivery')], max_length=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='payment',
            field=models.CharField(blank=True, choices=[('C', 'Cash'), ('O', 'Online Payment Provider'), ('V', 'Visa')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='CartItem', to='carts.CartItem'),
        ),
    ]
