# Generated by Django 3.2.9 on 2022-03-25 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0027_cart_recieved'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online Payment', 'Online Payment Provider'), ('Visa', 'Visa')], max_length=50)),
                ('delivery', models.CharField(blank=True, choices=[('Pick-up', 'Pick-up'), ('Normal Delivery', 'Normal Delivery'), ('Fast Delivery', 'Fast Delivery')], max_length=50)),
                ('sent', models.BooleanField(default=False)),
                ('recieved', models.BooleanField(default=False)),
                ('total', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(related_name='OrderItem', to='carts.OrderItem')),
            ],
        ),
    ]
