# Generated by Django 3.2.9 on 2022-02-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
