# Generated by Django 3.2.9 on 2022-03-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='ordersystem/staticfiles/rest_framework/img/'),
        ),
    ]
