# Generated by Django 3.2.9 on 2022-02-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_product_owner'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_items',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='products.Product'),
        ),
    ]
