# Generated by Django 3.2.9 on 2022-02-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_product_quantity'),
        ('carts', '0012_alter_cart_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_items',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
