# Generated by Django 3.2.9 on 2022-03-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0021_auto_20220301_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
