# Generated by Django 3.2.9 on 2022-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0025_auto_20220322_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
