# Generated by Django 3.2.9 on 2022-03-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0028_auto_20220325_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='recieved',
            new_name='received',
        ),
    ]
