# Generated by Django 3.2.9 on 2022-03-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0029_rename_recieved_cart_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='received',
        ),
    ]
