# Generated by Django 3.2.9 on 2022-03-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0031_cart_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='recieved',
            new_name='received',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='received',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sent',
        ),
    ]
