# Generated by Django 3.2.9 on 2022-03-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0032_auto_20220325_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
    ]
