# Generated by Django 3.2.9 on 2022-01-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inStock',
            field=models.BooleanField(default=False),
        ),
    ]
