# Generated by Django 3.2.9 on 2022-01-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
